export const subject = [
      {
            sem : 1,
            sub1 : "Data Structure and Algoritham",
            sub1Code:"PCCS401",
            sub2 : "English",
            sub2Code:"PCCS402",
            sub3 : "C++",
            sub3Code:"PCCS403",
            sub4 : "Java",
            sub4Code:"PCCS404",
            sub5 : "Operating System",
            sub5Code:"PCCS405",
            sub6 : "Computer Architecture",
            sub6Code:"PCCS405",
      },
      {
            sem : 2,
            sub1 : "Database Management SYstem",
            sub1Code:"PCCS406",
            sub2 : "Compiler Designer",
            sub2Code:"PCCS407",
            sub3 : "Python", 
            sub3Code:"PCCS408",
            sub4 : "JavaScript",
            sub4Code:"PCCS409",
            sub5 : "Software Engineering",
            sub5Code:"PCCS4010",
            sub6 : "Computer Network",
            sub6Code:"PCCS4011"

      },
      {
            sem : 3,
            sub1 : "Data Structure and Algoritham",
            sub1Code:"PCCS4012",
            sub2 : "English",
            sub2Code:"PCCS4013",
            sub3 : "C++",
            sub3Code:"PCCS4014",
            sub4 : "Java",
            sub4Code:"PCCS4015",
            sub5 : "Operating System",
            sub5Code:"PCCS4016",
            sub6 : "Computer Architecture",
            sub6Code:"PCCS4017",
      },
      {
            sem : 4,
            sub1 : "Database Management SYstem",
            sub1Code:"PCCS4018",
            sub2 : "Compiler Designer",
            sub2Code:"PCCS4019",
            sub3 : "Python", 
            sub3Code:"PCCS4020",
            sub4 : "JavaScript",
            sub4Code:"PCCS4021",
            sub5 : "Software Engineering",
            sub5Code:"PCCS4022",
            sub6 : "Computer Network",
            sub6Code:"PCCS4023"
      },
      {
            sem : 5,
            sub1 : "Data Structure and Algoritham",
            sub1Code:"PCCS4024",
            sub2 : "English",
            sub2Code:"PCCS4025",
            sub3 : "C++",
            sub3Code:"PCCS4026",
            sub4 : "Java",
            sub4Code:"PCCS4027",
            sub5 : "Operating System",
            sub5Code:"PCCS4028",
            sub6 : "Computer Architecture",
            sub6Code:"PCCS4029",
      },
      {
            sem : 6,
            sub1 : "Database Management SYstem",
            sub1Code:"PCCS4030",
            sub2 : "Compiler Designer",
            sub2Code:"PCCS4031",
            sub3 : "Python", 
            sub3Code:"PCCS4032",
            sub4 : "JavaScript",
            sub4Code:"PCCS4033",
            sub5 : "Software Engineering",
            sub5Code:"PCCS40134",
            sub6 : "Computer Network",
            sub6Code:"PCCS40135"
      },
      {
            sem : 7,
            sub1 : "Data Structure and Algoritham",
            sub1Code:"PCCS4036",
            sub2 : "English",
            sub2Code:"PCCS4037",
            sub3 : "C++",
            sub3Code:"PCCS4038",
            sub4 : "Java",
            sub4Code:"PCCS4039",
            sub5 : "Operating System",
            sub5Code:"PCCS4040",
            sub6 : "Computer Architecture",
            sub6Code:"PCCS4041",
      },
      {
            sem : 8,
            sub1 : "Database Management SYstem",
            sub1Code:"PCCS4041",
            sub2 : "Compiler Designer",
            sub2Code:"PCCS4042",
            sub3 : "Python", 
            sub3Code:"PCCS4043",
            sub4 : "JavaScript",
            sub4Code:"PCCS4044",
            sub5 : "Software Engineering",
            sub5Code:"PCCS40145",
            sub6 : "Computer Network",
            sub6Code:"PCCS40146"
      }
] ;


export const subjectResult = [
      {
            sem : 1,
            sub1 :9.0,
            sub1Credit :4,
            sub1Code:"PCCS401",
            sub2 : 8.0,
            sub2Credit :3,
            sub2Code:"PCCS402",
            sub3 : 7.0,
            sub3Credit :4,
            sub3Code:"PCCS403",
            sub4 : 8.0,
            sub4Credit :2,
            sub4Code:"PCCS404",
            sub5 : 8.0,
            sub5Credit :4,
            sub5Code:"PCCS405",
            sub6 : 6.0,
            sub6Credit :4,
            sub6Code:"PCCS405",
      },
      {
            sem : 2,
            sub1 :7.0,
            sub1Credit :4,
            sub1Code:"PCCS401",
            sub2 : 8.0,
            sub2Credit :4,
            sub2Code:"PCCS402",
            sub3 : 7.0,
            sub3Credit :4,
            sub3Code:"PCCS403",
            sub4 : 9.0,
             sub4Credit :4,
            sub4Code:"PCCS404",
            sub5 : 8.0,
             sub5Credit :3,
            sub5Code:"PCCS405",
            sub6 : 7.0,
            sub6Credit :4,
            sub6Code:"PCCS405",

      },
      {
            sem : 3,
            sub1 :9.0,
            sub1Credit :4,
            sub1Code:"PCCS401",
            sub2 : 8.0,
            sub2Credit :4,
            sub2Code:"PCCS402",
            sub3 : 7.0,
            sub3Credit :4,
            sub3Code:"PCCS403",
            sub4 : 8.0,
            sub4Credit :4,
            sub4Code:"PCCS404",
            sub5 : 9.0,
            sub5Credit :4,
            sub5Code:"PCCS405",
            sub6 : 7.0,
            sub6Credit :4,
            sub6Code:"PCCS405",
      },
      {
            sem : 4,
            sub1 :8.0,
            sub1Credit :4,
            sub1Code:"PCCS401",
            sub2 : 8.0,
            sub2Credit :4,
            sub2Code:"PCCS402",
            sub3 : 7.0,
            sub3Credit :4,
            sub3Code:"PCCS403",
            sub4 : 8.0,
            sub4Credit :4,
            sub4Code:"PCCS404",
            sub5 : 8.0,
            sub5Credit :4,
            sub5Code:"PCCS405",
            sub6 : 6.0,
            sub6Credit :4,
            sub6Code:"PCCS405",
      },
      {
            sem : 5,
            sub1 :7.0,
            sub1Credit :4,
            sub1Code:"PCCS401",
            sub2 : 9.0,
            sub2Credit :4,
            sub2Code:"PCCS402",
            sub3 : 6.0,
            sub3Credit :4,
            sub3Code:"PCCS403",
            sub4 : 8.0,
            sub4Credit :4,
            sub4Code:"PCCS404",
            sub5 : 9.0,
            sub5Credit :4,
            sub5Code:"PCCS405",
            sub6 : 8.0,
            sub6Credit :4,
            sub6Code:"PCCS405",
      },
      {
            sem : 6,
            sub1 :9.0,
            sub1Credit :4,
            sub1Code:"PCCS401",
            sub2 : 8.0,
            sub2Credit :4,
            sub2Code:"PCCS402",
            sub3 : 7.0,
            sub3Credit :4,
            sub3Code:"PCCS403",
            sub4 : 8.0,
            sub4Credit :4,
            sub4Code:"PCCS404",
            sub5 : 9.0,
            sub5Credit :4,
            sub5Code:"PCCS405",
            sub6 : 10.0,
            sub6Credit :4,
            sub6Code:"PCCS405",
      },
      {
            sem : 7,
            sub1 :10.0,
            sub1Credit :4,
            sub1Code:"PCCS401",
            sub2 : 9.0,
            sub2Credit :4,
            sub2Code:"PCCS402",
            sub3 : 7.0,
            sub3Credit :4,
            sub3Code:"PCCS403",
            sub4 : 9.0,
            sub4Credit :4,
            sub4Code:"PCCS404",
            sub5 : 8.0,
            sub5Credit :4,
            sub5Code:"PCCS405",
            sub6 : 7.0,
            sub6Credit :4,
            sub6Code:"PCCS405",
      },
      {
            sem : 8,
            sub1 :9.0,
            sub1Credit :4,
            sub1Code:"PCCS401",
            sub2 : 10.0,
            sub2Credit :4,
            sub2Code:"PCCS402",
            sub3 : 9.0,
            sub3Credit :4,
            sub3Code:"PCCS403",
            sub4 : 8.0,
            sub4Credit :4,
            sub4Code:"PCCS404",
            sub5 : 8.0,
            sub5Credit :4,
            sub5Code:"PCCS405",
            sub6 : 9.0,
            sub6Credit :4,
            sub6Code:"PCCS405",
      }
] ;

